services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Behat\:
        resource: 'Tests\Behat\Context\*'
        tags: ['behat.context']

    Tests\Behat\State\ScenarioState:
        public: true

    Tests\Behat\Context\ApiContext:
        public: true
        arguments:
            $state: '@Tests\Behat\State\ScenarioState'
