parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer: ~

    App\Infrastructure\Console\Command\MakePolicyCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Infrastructure\Common\Library\Render\StubRenderer:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Infrastructure\Security\Token\JwtGenerator:
        arguments:
            $secret: '%env(string:JWT_SECRET)%'
            $ttl: '%env(int:JWT_TTL)%'

    App\Infrastructure\Security\Token\JwtDecoder:
        arguments:
            $secret: '%env(string:JWT_SECRET)%'

    App\Presentation\Http\Resolver\CurrentUserValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 200 }

    App\Infrastructure\Common\Library\Serializer\StringValueObjectDenormalizer:
        tags: [ 'serializer.normalizer' ]

    App\Application\ShortenUrl\Action\GenerateUniqueAliasAction:
        arguments:
            $length: 5
